# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d01be2e2a770e769e5c82b67ccfae13e154aa3f28cf63c5f2de7762fe9797692f57d0f3605942dc9df2d2bda4818f50cc120167c80c828183ac236b0e55d1b6

test:
  secret_key_base: bdecac4f1a3a5d1d733e4a9c26ceb8e1bad1939fd6a3118aa311e656522a2422904dbc4264fe35ccc3546f4354a79ff87c597154afa9abb40b4d14db8be0f69b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
